//
// Copyright (c) 2026 AIRBUS and its affiliates.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//

package Apollo11Model {
	
	//Analysis folder
	private import AnalysisPackage::*;
	private import CalculationsPackage::*;
	
	//CoSMA folder
	private import CoSMAPackage::*;
	private import CoSMAViewsPackage::*;
	private import CoSMAQuantitiesAndUnitsPackage::*;
	
	//Execution folder
	private import Apollo11MissionExecutionPackage::*;
	
	//Function folder
	private import FunctionsPackage::*;
	private import FunctionSpecificationPackage::*;
	
	//Logical folder
	private import LogicalComponentsPackage::*;
	
	//Purpose folder
	private import CapabilitiesPackage::*;
	private import ContextPackage::*;
	private import MissionPackage::*;
	private import MissionPhasesPackage::*;
	private import MissionSpecificationPackage::*;
	private import StakeholderPackage::*;
	
	//Operation folder
	private import OperationsPackage::*;
	
	//Program folder
	private import ProgramPackage::*;
	
	//Requirements folder
	private import FunctionalRequirementsPackage::*;
	private import MissionRequirementsPackage::*;
	private import StakeholderNeedsPackage::*;
	private import TechnicalRequirementsPackage::*;
	
	//Technical folder
	private import AstronautsPackage::*;
	private import SystemPackage::*;
	private import SystemSpecificationPackage::*;
	private import TechnicalComponentsPackage::*;
	private import TechnicalIndividualsPackage::*;
	private import TechnicalPortsPackage::*;
}